spring:
  application:
  name: abnormalityAccept
  profiles:
    active: dev



jwt:
  keybase: abnormality


abnormality:
  jwt:
    header: abnormality
    expire: 604800 # 7天
    secret: abnormalityabnormalityabnormality

pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致