server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://poyuan.kmdns.net:3306/abnormality?useSSL=false&serverTimezone=UTC
    username: abnormality
    password: abnormality
    driver-class-name: com.mysql.cj.jdbc.Driver

    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://poyuan.kmdns.net:3306/abnormality?useSSL=false&serverTimezone=UTC
          username: abnormality
          password: abnormality
          driver-class-name: com.mysql.cj.jdbc.Driver

        slave:
          url: jdbc:mysql://poyuan.kmdns.net:13306/abnormality?useSSL=false&serverTimezone=UTC
          username: abnormality
          password: abnormality
          driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.abnormality.abnormalityaccept.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true

minio:
  endpoint: http://poyuan.kmdns.net:19000
  username: minioadmin
  password: minioadmin
  bucketName: abnormality

logging:
  level:
    com.baomidou.dynamic.datasource: debug
