spring:
  application:
  name: abnormalityAccept
  profiles:
    active: dev

abc:
  dce: sdas112251510510502

#注意：yml格式的配置文件的子节点字段冒号后面必须有空格，否则会报错
sds:
  #正确
  eg2: sssssssssssssssssssssssss

jwt:
  keybase: abnormality